[[constraint]]
  name = "github.com/avast/retry-go"
  version = "1.0.2"

[[constraint]]
  name = "github.com/gdamore/tcell"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/lunixbochs/vtclean"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/rivo/tview"

[[constraint]]
  branch = "zsh-completion-custom"
  name = "github.com/spf13/cobra"
  source = "github.com/rsteube/cobra"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.2.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "github.com/tcnksm/go-gitconfig"
  version = "0.1.2"

[[constraint]]
  name = "github.com/xanzy/go-gitlab"
  version = "0.11.7"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[prune]
  go-tests = true
  unused-packages = true
